### PR TITLE
Client agnostic

### PR DESCRIPTION
**Pull request by anjor**

### CODE REVIEW

**Comment by ibnesayeed** [comment]
@anjor I see what you are trying to do, but I am afraid there are too many pieces that are IA-specific in this code to show the statistics of preparation side. I am not sure that can be generalized unless we have a data model that we can expect from other clients.

Should a fork or branch be maintained just for the Filecoin-specific reporting? I also acknowledge that the code is not very readable due to cryptic variable names and lack of refactoring, which evolved from a little script in a hacky way.

**Comment by anjor** [comment]
@ibnesayeed don't worry about it. I accidentally opened the PR against the main repo. I have my own fork that I am working on.

**Comment by anjor** [comment]
I might do some code cleanup on my end -- if I end up doing that, would you be interested in taking those changes as well? 

Not to worry, I won't touch the IA specific stuff.

**Comment by ibnesayeed** [comment]
Of course, any changes and improvements are welcome.

I am also trying to think of ways to make the script pluggable, so there are basic stats, but client-specific stats can be plugged in. [Multipage apps](https://docs.streamlit.io/library/get-started/multipage-apps) are one way, but the stats will be segregated, hence won't benefit from side-by-side comparisons.

**Comment by anjor** [comment]
Also thank you so much for working on this. It was a great starting point for me to build on top of.

**Pull request closed without merging**
